apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:controller:service-serving-cert-signer
  namespace: openshift-service-cert-signer
roleRef:
  kind: Role
  name: system:openshift:controller:service-serving-cert-signer
subjects:
- kind: ServiceAccount
  namespace: openshift-service-cert-signer
  name: service-serving-cert-signer-sa
